modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (26 is current forge version)
[[mods]] #mandatory
modId="cdmmm" #mandatory
version="1.0" #mandatory
displayName="Meat Miner" #mandatory
logoFile="meatminer.png" #optional
authors="CrimsonDawn45" #optional
description='''
Mine your meat instead of using those boring old fashoned animal things!
After all it's called MINEcraft not FarmCraft lol.
'''
[[dependencies.cdmmm]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.cdmmm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
